[aws]
disabled = true

[[battery.display]]
threshold = 90

[cmake]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[package]
disabled = true
